### PR TITLE
add support for badge icon with count

### PR DESCRIPTION
**Pull request by hashimsayed0**
I've added an optional argument to CollapsibleItem called badgeCount. If it is passed, a badge is shown with backgroundColor and textColor as badgeBackgroundColor and badgeTextColor respectively, which are passed as optional arguments to CollapsibleSidebar. If badgeCount is null or zero, then the normal icon is displayed.

### CODE REVIEW

**Comment by hashimsayed0** [comment]
Apologies, just saw there was another PR for badges.

**Comment by DrunkOnBytes** [comment]
Hi @hashimsayed0, you can send another PR for badges. The older one which you saw, the person has not replied on it for a long time.

**Review by DrunkOnBytes — COMMENTED** [review]
Safe to merge

**Review by DrunkOnBytes — APPROVED** [review]
approved

**Comment by DrunkOnBytes** [comment]
Thank you @hashimsayed0 for this PR.
The badge feature was a requested feature from the community as well. 🎉🎉🎉

**Pull request merged**
