### PR TITLE
 - Added side menu

### PR DESCRIPTION
**Pull request by maliksenpai**

### CODE REVIEW

**Comment by DrunkOnBytes** [comment]
Hi @maliksenpai, your PR is not working properly as expected.
I tested it and saw that it is adding side menu's automatically to all even (mod 2) items of the sidebar.
We can't even customize the side menu levels or their titles. I think you were trying out an example and forgot to remove the example code.
The code you have written is great, please fix these small errors and push another PR. I'll definitely review it and approve it if it works.

**Comment by maliksenpai** [comment]
Thanks, but I'm not sure about customize side levels. Can we chat about on discord @DrunkOnBytes ? 
image

**Comment by DrunkOnBytes** [comment]
Sure, you can ping me on DrunkOnBytes #4940

**Comment by maliksenpai** [comment]
@DrunkOnBytes hello, I have sent friend request 5 days ago, can you look at? MalikSenpai#8572

**Pull request closed without merging**
