### PR TITLE
Show Title Argument

### PR DESCRIPTION
**Pull request by ShaunAtSense**
Added a showTitle argument that allows the Title and Avatar Image to be hidden.

### CODE REVIEW

**Comment by DrunkOnBytes** [comment]
Hi @ShaunAtSense, can you please add a description for this pull request to describe what new feature you have added.

**Comment by ShaunAtSense** [comment]
Hi @DrunkOnBytes, updated as requested. First contribution, so let me know if there is something else missing.

**Comment by ShaunAtSense** [comment]
Hi @DrunkOnBytes, let me know if you intend on merging the pull request.

**Comment by DrunkOnBytes** [comment]
Hi @ShaunAtSense, will do it by tonight.

**Comment by DrunkOnBytes** [comment]
Hi @ShaunAtSense, I have merged the PR. I made a small change to your code in the final published version on pub.
I changed `Container( )` to `const SizedBox( )` to improve runtime performance.
Thanks a lot for helping out on this project.

Hope you will continue to contribute to this project and many other open source projects as well. 😄

**Pull request merged**
